### ISSUE TITLE
Create product function doesn't appear

### ISSUE THREAD

**Issue by Dylan2388** [endevver/mt-plugin-storefront#1]
Hi,

I'm just a newbie to Movable Type and I'm trying to create a e-commerce-like-website by using Movable Type. I heard that this plugin can help me create a website demo like that, but when I installed and trying to use, the "Product" option doesn't appear on the drop down list.

I notice that there is "Store" option in my menu, which means I did successfully install the plugin, am I right?
Btw, the version of Movable Type that I'm using right now is  6.3.7 with with AWS.
If anyone have the answer to my problem, that would be really helpful.
Thanks
![capture](https://user-images.githubusercontent.com/42316243/49139783-3991dc00-f325-11e8-9624-6d5af6ceb0fa.PNG)

**Comment by danwolfgang** [comment]
Hey Dylan — I doubt this works with MT 6 as the reader specifically notes it’s only for MT 4. That may be the problem, I don’t know. Certainly, as the last update was six years ago, it’s basically from a different era!

**Comment by dylanpnlearn** [comment]
Thank you for your answer. I do realize that when trying to dig deeper into new version now. Seems like I need to find another solution then.

**Comment by Dylan2388** [comment]
Thank you for your answer. I realize this now when trying to dig deeper into the new version. It seems like I have to find another way to do it.
